# coding: utf-8
user = User.find_by_username 'lucien.farstein@gmail.com'
!user.nil? && User.create(username: 'lucien.farstein@gmail.com', password: 'toto555500')

[['#CECECE','Argenté'],
 ['#F3F3D6','Beige'],
 ['#FFFFFF','Blanc'],
 ['#00b2e7','Bleu'],
 ['#be0926','Bordeaux'],
 ['#614E1A','Bronze'],
 ['#FEC3AC','Chair'],
 ['#B36700','Cuivré'],
 ['#FFFF99','Doré'],
 ['#FEFEE0','Écru'],
 ['#e41370','Fuchsia'],
 ['#8c8c8c','Gris'],
 ['#fffff0','Ivoire'],
 ['#fcea10','Jaune'],
 ['#94812B','Kaki'],
 ['#935b38','Marron'],
 ['#D473D4','Mauve'],
 ['#FFF','Multicolore'],
 ['#000000','Noir'],
 ['#f29400','Orange'],
 ['#811453','Prune'],
 ['#f2aac6','Rose'],
 ['#FF0000','Rouge'],
 ['#463F32','Taupe'],
 ['#FFFFF0','Transparent'],
 ['#00a096','Turquoise'],
 ['#007325','Vert'],
 ['#980d7d','Violet']].each do |e|
  Color.create!(hex: e[0], name: e[1])
end

[
  ['ACAJOU','Acajou'], ['ACIER','Acier'], ['ACRYLIQUE','Acrylique'], ['ALPAGA','Alpaga'],
  ['ALUMINIUM','Aluminium'],['AMBRE','Ambre'],['ANGORA','Angora'],['ARDOISE','Ardoise'],
  ['ARGENT','Argent massif'],['ARGENTSF','Argent silver filled'],['ARGILE','Argile'],
  ['AUTRE','Autre'],['BAMBOU','Bambou'],['BOIS','Bois'],['BOISF','Bois flotté'],
  ['BRONZE','Bronze'],['CACHEMIRE','Cachemire'],['CARTON','Carton'],['CERAMIQUE','Céramique'],
  ['CHENE','Chêne'],['CIRE','Cire'],['COCO','Coco'],['COQUIL','Coquillage'],['CORAIL','Corail'],
  ['COTON','Coton'],['COTONEN','Coton enduit'],['CRISTAL','Cristal'],
  ['CRISSWAR','Cristal swarovski'],
  ['CUIR','Cuir'],
  ['CUIVRE','Cuivre'],
  ['DAIM','Daim'],
  ['DENTELLE','Dentelle'],
  ['ELASTANE','Elasthanne'],
  ['EMAIL','Email'],
  ['ETAIN','Etain'],
  ['FAIENCE','Faïence'],
  ['FFOURRURE','Fausse fourrure'],
  ['FER','Fer'],
  ['FEUTRINE','Feutrine'],
  ['FIBREM','Fibres mélangées'],
  ['FICELLE','Ficelle'],
  ['FILCOUT','Fil de couture'],
  ['FILFER','Fil de fer'],
  ['FILNYLON','Fil de nylon'],
  ['FIMO','Fimo'],
  ['FLANELLE','Flanelle'],
  ['FOURRURE','Fourrure'],
  ['GOUACHE','Gouache'],
  ['GRAINE','Graine'],
  ['GRES','Grès'],
  ['HETRE','Hêtre'],
  ['HUILE','Huile'],
  ['IVOIRE','Ivoire'],
  ['IVOIREV','Ivoire végétal'],
  ['JADE','Jade'],
  ['JEAN','Jean'],
  ['JUTE','Jute'],
  ['LAINE','Laine'],
  ['LAINEF','Laine feutrée'],
  ['LAITON','Laiton'],
  ['LATEX','Latex'],
  ['LIEGE','Liège'],
  ['LIN','Lin'],
  ['MARBRE','Marbre'],
  ['MATVEGET','Matières végétales'],
  ['MERINOS','Mérinos'],
  ['MERISIER','Merisier'],
  ['METAL','Métal'],
  ['METALAR','Métal argenté'],
  ['METALBRONZ','Métal couleur bronze'],
  ['METALCUIVR','Métal couleur cuivre'],
  ['METALOR','Métal doré'],
  ['MOHAIR','Mohair'],
  ['MOSAIQUE','Mosaique'],
  ['MOUSSE','Mousse'],
  ['MOUSSELINE','Mousseline'],
  ['NACRE','Nacre'],
  ['NOYER','Noyer'],
  ['NYLON','Nylon'],
  ['ORPURE','Or'],
  ['ORBLANC','Or Blanc'],
  ['ORGF','Or gold filled'],
  ['ORJAUNE','Or Jaune'],
  ['ORROSE','Or Rose'],
  ['ORGANZA','Organza'],
  ['OSCORNE','Os, corne'],
  ['PAPIER','Papier'],
  ['PASTEL','Pastel'],
  ['POLY','Pâte polymère'],
  ['PEAUX','Peaux'],
  ['PERLE','Perle'],
  ['PERLECHAL','Perle au chalumeau'],
  ['PERLEVER','Perle de verre'],
  ['PIERRE','Pierre'],
  ['PIERSEMI','Pierre de gemmes'],
  ['PIERPRC','Pierre précieuses'],
  ['PIERFINE','Pierres fines'],
  ['PIERORGA','Pierres organiques'],
  ['PIERSYNT','Pierres synthétiques'],
  ['PIN','Pin'],
  ['PARGENT','Plaqué Argent'],
  ['POR','Plaqué Or'],
  ['PLASTIQUE','Plastique'],
  ['PLATINE','Platine'],
  ['PLATRE','Plâtre'],
  ['PLUME','Plume'],
  ['POLAIRE','Polaire'],
  ['POLYESTER','Polyester'],
  ['POLYETHILENE','Polyéthylène'],
  ['POLYSTIRENE','Polystyrène'],
  ['PORCELAINE','Porcelaine'],
  ['PORCEFROIDE','Porcelaine froide'],
  ['RESINE','Résine'],
  ['RHODIUM','Rhodium'],
  ['ROCAILLE','Rocaille'],
  ['SABLES','Sables'],
  ['SATIN','Satin'],
  ['SILICONE','Silicone'],
  ['SIMILICU','Simili cuir'],
  ['SOIE','Soie'],
  ['STRASS','Strass'],
  ['STRETCH','Stretch'],
  ['SUEDINE','Suédine'],
  ['SYNTHETIQUE','Synthétique'],
  ['TAFFETAS','Taffetas'],
  ['TEK','Tek'],
  ['TERRECUITE','Terre cuite'],
  ['TISSU','Tissu'],
  ['TISSUJAP','Tissu japonais'],
  ['TITANE','Titane'],
  ['TOILE','Toile'],
  ['TOILECIR','Toile cirée'],
  ['TOILEJOUY','Toile de jouy'],
  ['TOILEEND','Toile enduite'],
  ['TULLE','Tulle'],
  ['VEGETAL','Vegetal'],
  ['VELOURS','Velours'],
  ['VELOURSC','Velours Côtelé'],
  ['VERMEIL','Vermeil'],
  ['VERRE','Verre'],
  ['VINYLE','Vinyle'],
  ['VISCOSE','Viscose'],
  ['ZINC','Zinc']].each do |e|
  Material.create!(name: e[0], value: e[1])
end
